CREATE TABLE IF NOT EXISTS `CUSTOMER` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `FIRST_NAME` varchar(50) NOT NULL,
 `LAST_NAME` varchar(50) NOT NULL,
 `USER_NAME` varchar(50) NOT NULL,
 PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `LOCATION` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(50) NOT NULL,
 `COUNTRY` varchar(50) NOT NULL,
 `CITY` varchar(50),
 `COUNTY` varchar(50),
 `STREET_ADDRESS` varchar(1000) NOT NULL,
 PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ORDER` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `SHIPPED_FROM_LOCATION` bigint(20) NOT NULL,
 `CUSTOMER` bigint(20) NOT NULL,
 PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PRODUCT` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(50) NOT NULL,
 `DESCRIPTION` varchar(1000),
 `PRICE` DECIMAL(2, 2),
 `WEIGHT`DECIMAL(2, 2),
 `PRODUCT_CATEGORY` bigint(20) NOT NULL,
 `SUPPLIER` bigint(20) NOT NULL,
 PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PRODUCT_CATEGORY` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(50) NOT NULL,
 `DESCRIPTION` varchar(1000),
 PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SUPPLIER` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(50) NOT NULL,
 PRIMARY KEY (`ID`)
);
